# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
# image: node:8

options:
  max-time: 60

clone: # the 'clone' section
  depth: 1 # the depth, in this case the clone will contain last commit

pipelines:
  branches:
    master:
      - step:
          name: Sentry Release
          image: getsentry/sentry-cli
          script:
            - sentry-cli releases -o "${SENTRY_ORG}" new -p "${SENTRY_PROJECT}" "${BITBUCKET_BUILD_NUMBER}"
            - sentry-cli releases -o "${SENTRY_ORG}" set-commits --auto "${BITBUCKET_BUILD_NUMBER}"
      - step:
          # caches:
          #   - node
          script:
            - >
              ssh bitbucket@direct.onova.co /bin/bash << EOF
                echo "connected to `hostname` as $USER";
                cd /var/www/server.data &&
                git fetch &&
                git reset --hard origin/master &&
                yarn &&
                pm2 reload server.data --silent --no-color;
              EOF
      - step:
          name: Sentry Finalize Release & Deploy
          deployment: production
          image: getsentry/sentry-cli
          script:
            - sentry-cli releases -o "${SENTRY_ORG}" finalize "${BITBUCKET_BUILD_NUMBER}"
            - sentry-cli releases -o "${SENTRY_ORG}" deploys "${BITBUCKET_BUILD_NUMBER}" new -e "production"
