##
# You should look at the following URL's in order to grasp a solid understanding
# of Nginx configuration files in order to fully unleash the power of Nginx.
# http://wiki.nginx.org/Pitfalls
# http://wiki.nginx.org/QuickStart
# http://wiki.nginx.org/Configuration
#
# Generally, you will want to move this file somewhere, and start with a clean
# file but keep this around for reference. Or just disable in sites-enabled.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Expires map
map $sent_http_content_type $expires {
    default                    off;
    text/html                  max; # static html
    text/css                   max;
    application/javascript     max;
    ~image/                    max;
}

server {

        # SSL configuration
        #
        # listen 443 ssl default_server;
        # listen [::]:443 ssl default_server;
        #
        # Note: You should disable gzip for SSL traffic.
        # See: https://bugs.debian.org/773332
        #
        # Read up on ssl_ciphers to ensure a secure configuration.
        # See: https://bugs.debian.org/765782
        #
        # Self signed certs generated by the ssl-cert package
        # Don't use them in a production server!
        #
        # include snippets/snakeoil.conf;

#       root /var/www/webapp/build;

        # Add index.php to the list if you are using PHP
#       index index.html index.htm index.nginx-debian.html;

        server_name drop.uno;

        location ~ /.well-known/apple-app-site-association {
            root /var/www/webapp-drop/dist;
            default_type application/pkcs7-mime;
        }

        # webapp SSR
        location / {
                proxy_pass http://localhost:3002;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
                client_max_body_size 60m;
        }

        if ($host = www.drop.uno) {
            return 301 https://drop.uno$request_uri;
        }

        listen [::]:443 ssl http2; # managed by Certbot
        listen 443 ssl http2; # managed by Certbot
        ssl_certificate /etc/letsencrypt/live/drop.uno/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/drop.uno/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot

        ssl_stapling on;
        ssl_stapling_verify on;
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

        # config to enable HSTS(HTTP Strict Transport Security) https://developer.mozilla.org/en-US/docs/Security/HTTP_Strict_Transport_Security
        # to avoid ssl stripping https://en.wikipedia.org/wiki/SSL_stripping#SSL_stripping
        # also https://hstspreload.org/
        #add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" preload;

        expires $expires;

        location /api/ {
            proxy_pass http://localhost:4040;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_send_timeout 600;
            proxy_read_timeout 600;
            send_timeout 600;
            client_max_body_size 60m;
        }
}

server {
    if ($host = www.drop.uno) {
        return 301 https://drop.uno$request_uri;
    } # managed by Certbot


    if ($host = drop.uno) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


    listen 80;
    listen [::]:80;

    server_name drop.uno www.drop.uno;
    return 404; # managed by Certbot
}
