// @flow
import axios from 'axios';

const NovaPoshta_URL = 'https://api.novaposhta.ua/v2.0/json';

export const NP = {
  // 1
  generated: 'np-generated',
  // 4, 6 or 101
  shipped: 'np-shipped',
  // 7 or 8
  delivered: 'np-delivered',
  // 102, 103 or 108
  // TODO: which one didn't collect
  refused: 'np-refused',
  // 9
  collected: 'np-collected',
  // TODO: which one didn't ship
};

export default class Shipping {
  static async getShippingStatus(trackingNumber: string): Promise<any> {
    return new Promise((resolve, reject) => {
      axios
        .post(`${NovaPoshta_URL}/documentsTracking/`, {
          modelName: 'TrackingDocument',
          calledMethod: 'getStatusDocuments',
          methodProperties: {
            Documents: [{ DocumentNumber: trackingNumber, Phone: '' }],
          },
        })
        .then(({ data }) => {
          if (!data.success) return reject(data);

          const result = data.data[0];

          // Number not found
          if (result.StatusCode === '3') {
            return resolve(false);
          }

          // e.g. convert `string` 08-05-2018 to a `Date` Tue May 08 2018
          const trackingNumberDate = new Date(
            result.ScheduledDeliveryDate.replace(
              /(\d{2})-(\d{2})-(\d{4})/,
              '$2/$1/$3'
            )
          );

          return resolve({
            raw: result,
            scheduledDeliveryDate: trackingNumberDate,
            status: this.getInternalStatus(result.StatusCode),
            statusCode: result.StatusCode,
            statusMessage: result.Status,
          });
        })
        .catch(error => reject(error));
    });
  }

  static getInternalStatus(statusCode: string): string | void {
    switch (statusCode) {
      case '1':
        return NP.generated;
      case '4':
      case '5':
      case '6':
      case '101':
        return NP.shipped;
      case '7':
      case '8':
        return NP.delivered;
      case '102':
      case '103':
      case '108':
        return NP.refused;
      case '9':
        return NP.collected;
      default:
        return;
    }
  }
}

export const buyerNeedsToPay = {
  data: {
    id: '9B27M6E',
    externalId: null,
    cartId: 574,
    productTitle: 'Кобзар 1846р',
    productPrice: 10000,
    productWeight: 1500,
    handlerPrice: 3500,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Ґіанфранцо',
    buyerLastName: 'Палумбо',
    buyerPatronymic: '',
    buyerPhone: '380977414301',
    buyerEmail: 'gianpa+buyer@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+seller@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-18T15:28:13.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '7b422fbe-e1b8-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 617,
      amount: 10000,
      commissionAmount: 1600,
      status: 'NEW',
      statusCode: 'NEEDS_CONFIRMATION',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: 'CONFIRMATION',
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttu2zAMfc5fGP0A6xbLSqAKyJaHBZjTrHUf+lQYDpG4bRxXsre2Xz9SToJUgGCSh6R8DmnLvQdYPkA9eHC2gBCqHSTN9vZms7iH92eRqZnJ9XRmtMpu3MTGsJtM7F/woTm2TqQ8lZadXUS6qnWZ0CbPcqWV4lrJ3DKKIliAr/dV26M9sVX9/mO1dpnUMy0sO7mEHMCvlo6PR44fzBjDlNBWB3AlhD45d0zKKvxu2tfEsghSVn0c2t5/OsOnlp0dAgb/5vZ9380ZEzJHCjwVc4WHFZsVu4fQHdsAG3+sUZKm3aUvobOMqrCYXZGwm4HsML730WxdUT5+3ZU7tX75k90tn77W5eJfsYz31jLKoMxt1YOTXBiBNxFmLs1cGMtiPGpzoN91guuUc9RmdAnp6MXFBSb0OhR5D95DW3+6mUH04hEEH0gNMA+HdrGJ1BUR+/PXaT51j3rjCLMc9VdTTUOKsVOrBvWUkqvYq4niWkbV2C9uCokVlwqtb8v2H1mwumk=',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/617/confirmations',
        },
      },
      payReceipt:
        'https://api.stage.uapay.ua/api/receipts/b6789f1b-6d74-4691-b908-f65370b9b1b9.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 616,
      amount: 3500,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.stage.uapay.ua/api/acquiring/receipts/escrowbox/9e9846af-1dbc-4b00-b0a7-686d1a299351.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const paymentWaitingProcessing = {
  data: {
    id: '9DB9T5K',
    externalId: null,
    sellerUserId: null,
    buyerUserId: null,
    cartId: 515,
    productTitle: 'kebab cat',
    productPrice: 199900,
    productWeight: 5000,
    handlerPrice: 5500,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Олександр',
    buyerLastName: 'Костінський',
    buyerPatronymic: '',
    buyerPhone: '380677929197',
    buyerEmail: 'gianpa+buyer@gmail.com',
    sellerFirstName: 'Олександр',
    sellerLastName: 'Костінський',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+seller@gmail.com',
    lg: 'uk',
    createdAt: '2018-12-20T16:27:57.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '7b422fbe-e1b8-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 901,
      amount: 189429,
      commissionAmount: 10471,
      status: 'NEW',
      statusCode: null,
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: 'PAY_PROCESSING',
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/4e759953-49fa-4f43-8925-6981eda4d7f9.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 900,
      amount: 5500,
      commissionAmount: 0,
      status: 'NEW',
      statusCode: null,
      statusText: null,
      type: 'ECOM',
      waitingFor: 'PAY_PROCESSING',
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/64fe2010-c871-4457-ba32-f43c706a393d.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const buyerPaidDeal = {
  data: {
    id: '9B27M6E',
    externalId: null,
    cartId: 599,
    productTitle: 'Кобзар 1846р',
    productPrice: 10000,
    productWeight: 1500,
    handlerPrice: 3500,
    status: 'PAID',
    reasonStep: null,
    buyerFirstName: 'Ґіанфранцо',
    buyerLastName: 'Палумбо',
    buyerPatronymic: '',
    buyerPhone: '380977414301',
    buyerEmail: 'gianpa+buyer@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+seller@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-22T10:49:06.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '7b422fbe-e1b8-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 1297,
      amount: 10000,
      commissionAmount: 1600,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttOwzAMfd5fVHxAc+ttUxZpsAcm0WlAeUZVZ7ECy0rSAvt77HSbRqSoto/t9BxbVzsHsHyGZnBgdAne128Qtdv5zWbxBF+vIk245KlKRSKTGzPRIWwmE/0NzrcHa0TMY6nZ2UWkq61JRVbkaa4ypXimZK4ZRREswTW72vZoT3TdfN2u1iaV2TQTmp1cQvbgVkvDxyPHD2aMYUqw9R5MBb6Pzh2jqvYPrf2INAsgZTWHwfbuaAqeaHZ2CBjcp9n1fTdjTMgcKfBYzBQeVm5W7Al8d7AeNu7QoCStfYvffacZVWExuyKhNwPZfnzvt92asnrh5XL1s65KUVaPx/Vy8VOOd64ZZVDmtu7BSC4KwaWMhJol05lAhiEetNnT7xrBs5hz1GZ0CenoxcUFJvQ6FHgPzoFtjmZaIHrxCIJfpAaYh0O72ETqioi+uz/Np+lRb8VzIWWukrSgIYXYqVWLekrJVejVBnE1o2rsFzaFxApLhda/ZfsDipm53Q==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1297/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/8cd4c37a-1278-44b8-8aa6-fe9fe07321ad.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1296,
      amount: 3500,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/1bfcb646-700c-498f-ae38-531105411d1f.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const sellerConfirmedResponse = {
  data: {
    id: 'KEYT6LM',
    externalId: null,
    cartId: 624,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 2100,
    status: 'CONFIRMED',
    reasonStep: null,
    buyerFirstName: 'Пшфтакфс',
    buyerLastName: 'Зфдгьіщ',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-23T09:17:07.000Z',
    adId: null,
    handler: {
      status: 'CREATED',
      statusCode: null,
      statusText: null,
      waybillNumber: 20600000076896,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: 'Київ',
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: 'Відділення №1: вул. Червонопрапорна, 34 (Корчувате)',
      recipientCityId: 'db5c88f5-391c-11dd-90d9-001a92567626',
      recipientCityName: 'Львів',
      recipientOfficeId: 'd6db6193-5620-11e5-8d8d-005056887b8d',
      recipientOfficeName: 'Відділення №66 (до 30 кг): вул. Городоцька,131',
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 1343,
      amount: 11111,
      commissionAmount: 1667,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttuwjAMfeYvKj6gudHLUBaJjYdVWhFi7HmqijXKRuiSdoN9/ewUEIsU1T7HdnJOo9dbBzB/gbp3YHQJ3lfvEDWb+/FytoKvN5FMuMxTqSTnk7EZ6QCb0Uh/g/PNwRoR81hqdkmRaStrEpHmWZKpVCmeKplpRiiSJbh6W9kO45Gu6q+HYmESmd6lQrNzSsweXDE3fFhy+GDFAFOBrfZg1uC76DIxWlf+ubEfkWaBpKr60NvOnUzOJ5pdEiJ692m2XddOGRMyQwk8FlOFi5XLgq3AtwfrYekONVrS2Pd451vNqAub2Y0Ivewp9sN5x2ZjyvUrL+fFZLErfsvd7Gcxn/2Uw77XjCqoclN1YCQXueBSRUJORTYV6GPAgzd7uq4RIosl4ueUmJZOnF1pYm+hoLt3Dmx9Mnc5R+GXjCg4ojTAOmy7xiTqRoh+fDr/n7pDvxXPZJ7wXCR0kQE7j2rQTym5CrOaYK5m1I3zwkshs8KjwujfY/sDsLK6AQ==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1343/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/6fb9874e-1825-47b8-9c36-85347e29f0db.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1342,
      amount: 2100,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/ebb46493-53b5-4496-a795-98bf8644a088.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const sellerCancelsAPaidDeal = {
  data: {
    id: 'ZS585UF',
    externalId: null,
    cartId: 639,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 2100,
    status: 'PAID',
    reasonStep: null,
    buyerFirstName: 'Пшфтакфс',
    buyerLastName: 'Зфдгьіщ',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-10-24T14:16:56.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 1373,
      amount: 11111,
      commissionAmount: 1667,
      status: 'REVERSED',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttOwzAMfd5fVHxAc1svm0KkQR+YRNAE2wNPqOosVmBZSVpgfD12dtGIWsX2sZ2cE+vlxgNUT9AMHoy2EEL9Ckm7vr5azB7h80VkY64mPJc8m6grM9IxbEYj/QU+tDtnRMpTqdnJRaSrnclEXhZZoXKleK5koRlFEbTgm03terRHum4+b+YPJpP5JBeaHV1CtuDnleGHJQ8bZhzClODqLZglhD45dUyWdbhv3XuiWQQpq9kNrvd7U/KxZieHgMF/mE3fd1PGhCyQAk/FVOFidjFnjxC6nQuw8LsGJWnda/oWOs2oCovZBQm9GMgOh/N+2rWxyxW3lc1s9by31Sqzv7NvW8X/WjPKoMx13YORXJSCy3Eiiil+nGsW41GbLV3XCFGkEvU9uoR0dOLsDBN6GYq8B+/BNXszKbHn2SMIfpAaYB6WnW0idUFE394d36fpUW/Fi0zSRcuCHinGjq1a1FNKrmKvNoqrGVVjvzgpJFYcKrT+Ddsfk3G53g==',
          },
          redirectUrl:
            'https://api.escrowbox.stage.uapay.ua/api/payments/1373/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/8732b397-45e8-4051-b24c-06dd802c4f94.pdf',
      reverseReceipt:
        'https://api.demo.uapay.ua/api/receipts/f607bf95-669c-49f6-95c8-9c7b5c745025.pdf',
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1372,
      amount: 2100,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/2955de75-7398-4c33-9cf7-222726457e56.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const dealConfirmationResp = {
  data: {
    id: 'E3319FS',
    externalId: null,
  },
};

export const buyerPaymentCVCFailure = {
  data: {
    id: '4Y3KDER',
    externalId: null,
    sellerUserId: null,
    buyerUserId: null,
    cartId: 480,
    productTitle: '2000 UAH price item',
    productPrice: 200000,
    productWeight: 3000,
    handlerPrice: 4100,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Олександр',
    buyerLastName: 'Костінський',
    buyerPatronymic: '',
    buyerPhone: '380977414301',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'жанфранко',
    sellerLastName: 'Палумбо',
    sellerPatronymic: '',
    sellerPhone: '380977414301',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-12-11T15:15:20.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 831,
      amount: 189524,
      commissionAmount: 10476,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"INVALID_CREDENTIAL","message":"Wrong CVV2 value","fields":{"cardFrom":{"securityCode":"INVALID_CREDENTIAL"}},"responseCode":"211","source":"TAS_P2P"}',
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/774aa739-0f9c-48d4-8e04-06d0e2096326.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 830,
      amount: 4100,
      commissionAmount: 0,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"WRONG_CVV","message":"Wrong CVV2 value","pluginId":"1","responseCode":"211","source":"TAS_ECOM"}',
      type: 'ECOM',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/47248767-47d8-4f8e-b66a-a1e33c3d086e.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

// from real payment
export const buyerPaymentFailureInsufficientFunds = {
  data: {
    id: 'Y18QS3U',
    externalId: null,
    sellerUserId: null,
    buyerUserId: null,
    cartId: 202,
    productTitle:
      'Жіночий  віндстопер Mammut\n- чудово рятуватиме від вітру та дощу\n- антомічний крій \n - подовжений рукав\n-  висока горловина\nРозмір  L  (може міти на М )\nCтан  5\nЗаміри\nа - 64\nв - 49\nс - 75\nЦіна  - 500 грн',
    productPrice: 56000,
    productWeight: 5000,
    handlerPrice: 6800,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Олександр',
    buyerLastName: 'Костінський',
    buyerPatronymic: '',
    buyerPhone: '380677929197',
    buyerEmail: 'isho@ukr.net',
    sellerFirstName: 'Андрій',
    sellerLastName: 'Головін',
    sellerPatronymic: '',
    sellerPhone: '380638047709',
    sellerEmail: 'outdoor.kyiv2013@gmail.com',
    lg: 'uk',
    createdAt: '2018-12-15T07:10:29.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '3fd42337-ed80-11e4-8a92-005056887b8d',
      senderOfficeName: null,
      recipientCityId: 'db5c88f5-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '39931b85-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 400,
      amount: 50000,
      commissionAmount: 6000,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"TECHNICAL_ERROR","message":"Insufficient funds","responseCode":"P2Ps2c101","source":"ALFA_P2P"}',
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: { confirmation: [Object] },
      payReceipt:
        'https://api.uapay.ua/api/receipts/60e4ccbd-bdbf-4f24-89bc-1ec0746ef047.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 399,
      amount: 6800,
      commissionAmount: 0,
      status: 'REVERSED',
      statusCode: 'REVERSED',
      statusText: null,
      type: 'ECOM',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.uapay.ua/api/acquiring/receipts/escrowbox/a8c2f39a-bb01-41d7-b0a3-23f47fb1385a.pdf',
      reverseReceipt:
        'https://api.uapay.ua/api/acquiring/receipts/escrowbox/a8c2f39a-bb01-41d7-b0a3-23f47fb1385a.pdf',
      finishReceipt: null,
    },
  },
};

export const buyerPaymentFailure = {
  data: {
    id: 'Z8QK927',
    externalId: null,
    cartId: 791,
    productTitle: "I don't know if you",
    productPrice: 11111,
    productWeight: 3000,
    handlerPrice: 3500,
    status: 'NEW',
    reasonStep: null,
    buyerFirstName: 'Тим',
    buyerLastName: 'Пррп',
    buyerPatronymic: '',
    buyerPhone: '380987987987',
    buyerEmail: 'gianpa+test@gmail.com',
    sellerFirstName: 'Алех',
    sellerLastName: 'Костінскї',
    sellerPatronymic: '',
    sellerPhone: '380677929197',
    sellerEmail: 'gianpa+test3@gmail.com',
    lg: 'uk',
    createdAt: '2018-11-01T15:36:03.000Z',
    adId: null,
    handler: {
      status: 'NEW',
      statusCode: null,
      statusText: null,
      waybillNumber: null,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: null,
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: null,
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: null,
      recipientOfficeId: '511fcf97-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: null,
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 1678,
      amount: 11111,
      commissionAmount: 1667,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"AUTHENTICATION_ERROR","message":"Internal server error","responseCode":"074","source":"TAS_P2P"}',
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/27a30371-a07d-4991-9d8f-a7f3c94e8edb.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 1677,
      amount: 3500,
      commissionAmount: 0,
      status: 'REJECTED',
      statusCode: 'REJECTED',
      statusText:
        '{"code":"INVALID_CREDENTIAL","message":"Unable to authenticate","pluginId":"1","responseCode":"074","source":"TAS_ECOM"}',
      type: 'ECOM_ONOVA',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/887db946-6623-42a1-b91d-6229f0aeda80.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

// we check novaPoshta to see if a package is shipped, not UAPAY
const sellerShippedPackage = {
  data: {
    id: '3YSEBLB',
    externalId: null,
    cartId: 409,
    productTitle: 'Great boots. Senator Docksides. Size 42 US',
    productPrice: 25000,
    productWeight: 3000,
    handlerPrice: 3600,
    status: 'SENT',
    reasonStep: null,
    buyerFirstName: 'Олександр',
    buyerLastName: 'Ковальський',
    buyerPatronymic: '',
    buyerPhone: '380977217884',
    buyerEmail: 'isho@ukr.net',
    sellerFirstName: 'Вовт',
    sellerLastName: 'Адад',
    sellerPatronymic: '',
    sellerPhone: '380977414301',
    sellerEmail: 'gianpa@gmail.com',
    lg: 'uk',
    createdAt: '2018-11-16T18:03:25.000Z',
    adId: null,
    handler: {
      status: 'CREATED',
      statusCode: '1',
      statusText: 'Нова пошта очікує надходження від відправника',
      waybillNumber: 20600000077982,
      senderCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      senderCityName: 'Київ',
      senderOfficeId: '1ec09d88-e1c2-11e3-8c4a-0050568002cf',
      senderOfficeName: 'Відділення №1: вул. Червонопрапорна, 34 (Корчувате)',
      recipientCityId: '8d5a980d-391c-11dd-90d9-001a92567626',
      recipientCityName: 'Київ',
      recipientOfficeId: '39931b76-e1c2-11e3-8c4a-0050568002cf',
      recipientOfficeName: 'Відділення №15: вул. Малинська, 18 (Новобіличи)',
      type: 'NovaPoshta',
    },
    productPayment: {
      id: 717,
      amount: 25000,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'P2P_ONOVA',
      waitingFor: null,
      details: {
        confirmation: {
          type: '3DS',
          url: 'https://acs.privatbank.ua/pPaReqMC.jsp',
          form: {
            PaReq:
              'eJxVUttuwjAMfeYvqn1AcyktDQqR2HgY0rox1j1PVbGgbIQuaXf5+9kpIBapqn2O7cTH1uXOASxeoO4dGF2A99UWomYzu1nN1/D5JtKxTJQYcyVzfmNGOsBmNNJf4HxztEbEPJaanV1k2sqaVGQTlaeZ4onKJ7nSjFAkC3D1rrId2iNd1Z+3y0eTykxlQrOTS8wB3HJh+HDk8MOIAaYAWx3AlOC76FwxKiv/0Nj3SLNAUlR97G3nfk3Ox5qdHSJ692F2XddOGRNygi3wWEwTPKxYLdkafHu0HlbuWKMkjd3Ge99qRlmYzK6a0KuebD/c99NsTFG+8mJfpEX5/P1ULsfFYv59+maaUQRFbqoOjOQiF0JkkeRTnkwlyhTwoM2Bnmtkim/jqM3gEtPSjfMLTew1FPrunQNb/xqVI3vxiIIfbA0oVbOLTU1dNaLv7k/zqTvUOxEikTLPJlLSkAJ2KtWgnjgeFWo1QVzNKBvrhU0hscJSofVv2f4AxHG56g==',
          },
          redirectUrl:
            'https://api.escrowbox.demo.uapay.ua/api/payments/717/confirmations',
        },
      },
      payReceipt:
        'https://api.demo.uapay.ua/api/receipts/a102ef28-e6dc-4ec1-8e85-a0e065e5c138.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
    handlerPayment: {
      id: 716,
      amount: 3600,
      commissionAmount: 0,
      status: 'PAID',
      statusCode: 'FINISHED',
      statusText: null,
      type: 'ECOM',
      waitingFor: null,
      details: null,
      payReceipt:
        'https://api.demo.uapay.ua/api/acquiring/receipts/escrowbox/ab11648d-776d-46dd-8ddc-a6c6ae443a38.pdf',
      reverseReceipt: null,
      finishReceipt: null,
    },
  },
};

export const novaPoshta = {
  // 1 - Tracking number generated. Waiting for seller to ship package.
  //
  // @SELLER please ship the item ASAP.
  generated: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '29-10-2018 21:24:51',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: '',
        CounterpartyType: '',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 0,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        WarehouseRecipientInternetAddressRef: '',
        MarketplacePartnerToken: '',
        DateScan: '0001-01-01 00:00:00',
        PaymentStatus: 'PREAUTH',
        PaymentStatusDate: '29.10.2018 21:25:56',
        AmountToPay: 73,
        AmountPaid: 0,
        InternationalDeliveryType: '',
        UndeliveryReasonsDate: '',
        RecipientWarehouseTypeRef: '',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        Status: 'Нова пошта очікує надходження від відправника',
        StatusCode: '1',
        RefEW: '00000000-0000-0000-0000-000000000000',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        SenderAddress: '',
        RecipientAddress: '',
        AnnouncedPrice: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 6 - Seller left the package. Ready to depart towards <city> - Estimated arrival time: XXX
  //
  // Item has been shipped. It should arrive on XXX
  shipped: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        DateScan: '17:17 30.10.2018',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        InternationalDeliveryType: '',
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        Status:
          'Відправлення у місті Львів. Очікуйте повідомлення про прибуття',
        StatusCode: '6',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // NOT USED - 41 - Preparing package to be shipped towards <city>
  preparedForDeparture: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        DocumentCost: 73,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseSender: 'Відділення №14 (до 30 кг): вул. Словацького, 5',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        DateScan: '21:35 30.10.2018',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        LastAmountTransferGM: '',
        LastAmountReceivedCommissionGM: '',
        InternationalDeliveryType: '',
        UndeliveryReasonsDate: '',
        AnnouncedPrice: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        Status: 'Готується до відправлення у місті Львів',
        StatusCode: '41',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 7 - Package arrived at office
  delivered: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        MarketplacePartnerToken: '***REMOVED***',
        DateScan: '10:24 31.10.2018',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        DocumentCost: 73,
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        DateFirstDayStorage: '2018-11-06',
        DateReturnCargo: '',
        InternationalDeliveryType: '',
        DaysStorageCargo: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        StorageAmount: '',
        StoragePrice: '',
        Status: 'Прибув у відділення',
        StatusCode: '7',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '2018-11-06 00:00:00',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 9 -
  collected: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        OwnerDocumentType: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        DateCreated: '31-10-2018 17:13:22',
        CheckWeight: 0,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '31.10.2018 16:52:04',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        MarketplacePartnerToken: '***REMOVED***',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        DateScan: '0001-01-01 00:00:00',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        LastAmountTransferGM: '',
        LastAmountReceivedCommissionGM: '',
        DocumentCost: 73,
        DocumentWeight: 5,
        AnnouncedPrice: '',
        UndeliveryReasonsDate: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        OwnerDocumentNumber: '',
        InternationalDeliveryType: '',
        WarehouseSender: 'Відділення №14 (до 30 кг): вул. Словацького, 5',
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        LoyaltyCardSender: '',
        LoyaltyCardRecipient: '9e221cd6-43ba-11e8-aa3a-0025b501a04b',
        Status: 'Відправлення отримано',
        StatusCode: '9',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },

  // 102 (was not retrieve from API) - entered manually
  refused: {
    success: true,
    data: [
      {
        Number: '20400106547369',
        DateCreated: '31-10-2018 17:13:22',
        DocumentWeight: 5,
        CheckWeight: 0,
        SumBeforeCheckWeight: 0,
        PayerType: 'Recipient',
        RecipientFullName: '',
        RecipientDateTime: '',
        OwnerDocumentType: '',
        ScheduledDeliveryDate: '01-11-2018',
        PaymentMethod: 'Cash',
        CargoDescriptionString: '',
        CargoType: 'Parcel',
        CitySender: 'Львів',
        CityRecipient: 'Львів',
        WarehouseRecipient: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
        CounterpartyType: 'PrivatePerson',
        Redelivery: 0,
        RedeliverySum: '',
        RedeliveryNum: '',
        RedeliveryPayer: '',
        AfterpaymentOnGoodsCost: '',
        ServiceType: 'WarehouseWarehouse',
        UndeliveryReasonsSubtypeDescription: '',
        WarehouseRecipientNumber: 15,
        LastCreatedOnTheBasisNumber: '',
        LastCreatedOnTheBasisDocumentType: '',
        LastCreatedOnTheBasisPayerType: '',
        LastCreatedOnTheBasisDateTime: '',
        LastTransactionStatusGM: '',
        LastTransactionDateTimeGM: '',
        WarehouseRecipientInternetAddressRef:
          '39931b85-e1c2-11e3-8c4a-0050568002cf',
        MarketplacePartnerToken: '***REMOVED***',
        DateScan: '10:24 31.10.2018',
        ClientBarcode: '',
        SenderAddress: '',
        RecipientAddress: '',
        CounterpartySenderDescription: '',
        CounterpartyRecipientDescription: '',
        CounterpartySenderType: 'PrivatePerson',
        PaymentStatus: 'PAYED',
        PaymentStatusDate: '30.10.2018 17:14:10',
        AmountToPay: 73,
        AmountPaid: 73,
        WarehouseRecipientRef: '490501cb-a33f-11e2-a57a-d4ae527baec3',
        DocumentCost: 73,
        AnnouncedPrice: '',
        OwnerDocumentNumber: '',
        DateFirstDayStorage: '2018-11-06',
        DateReturnCargo: '',
        InternationalDeliveryType: '',
        DaysStorageCargo: '',
        RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
        StorageAmount: '',
        StoragePrice: '',
        Status: 'Відмова одержувача',
        StatusCode: '102',
        RefEW: '5b22917c-dc56-11e8-a8ec-0025b502b06e',
        RedeliveryPaymentCardRef: '',
        RedeliveryPaymentCardDescription: '',
        CreatedOnTheBasis: '',
        DatePayedKeeping: '2018-11-06 00:00:00',
      },
    ],
    errors: [],
    warnings: [
      {
        ID_20400106547369:
          'Please enter a valid phone number from the express invoice to show full information',
      },
    ],
    info: [],
    messageCodes: [],
    errorCodes: [],
    warningCodes: [],
    infoCodes: [],
  },
};

let data = {
  Number: '20450072617861',
  Redelivery: 0,
  RedeliverySum: '',
  RedeliveryNum: '',
  RedeliveryPayer: '',
  OwnerDocumentType: '',
  LastCreatedOnTheBasisDocumentType: '',
  LastCreatedOnTheBasisPayerType: '',
  LastCreatedOnTheBasisDateTime: '',
  LastTransactionStatusGM: '',
  LastTransactionDateTimeGM: '',
  DateCreated: '07-05-2018 12:41:31',
  CheckWeight: 0,
  SumBeforeCheckWeight: 0,
  PayerType: 'Recipient',
  RecipientFullName: '',
  RecipientDateTime: '08.05.2018 13:36:49',
  ScheduledDeliveryDate: '08-05-2018',
  PaymentMethod: 'Cash',
  CargoDescriptionString: '',
  CargoType: 'Parcel',
  CitySender: 'Львів',
  CityRecipient: 'Чернівці',
  WarehouseRecipient:
    'Відділення №14 (до 30 кг на одне місце): вул. Небесної Сотні, 20',
  CounterpartyType: 'PrivatePerson',
  AfterpaymentOnGoodsCost: '',
  ServiceType: 'WarehouseWarehouse',
  UndeliveryReasonsSubtypeDescription: '',
  WarehouseRecipientNumber: 14,
  LastCreatedOnTheBasisNumber: '',
  WarehouseRecipientInternetAddressRef: '01ae25ec-e1c2-11e3-8c4a-0050568002cf',
  MarketplacePartnerToken: '***REMOVED***',
  ClientBarcode: '',
  SenderAddress: '',
  RecipientAddress: '',
  CounterpartySenderDescription: '',
  CounterpartyRecipientDescription: '',
  CounterpartySenderType: 'PrivatePerson',
  DateScan: '0001-01-01 00:00:00',
  PaymentStatus: 'PAYED',
  PaymentStatusDate: '06.05.2018 12:42:55',
  AmountToPay: 58,
  AmountPaid: 58,
  LastAmountTransferGM: '',
  LastAmountReceivedCommissionGM: '',
  DocumentCost: 58,
  DocumentWeight: 5,
  AnnouncedPrice: '',
  UndeliveryReasonsDate: '',
  RecipientWarehouseTypeRef: '841339c7-591a-42e2-8233-7a0a00f0ed6f',
  RedeliveryPaymentCardRef: '',
  RedeliveryPaymentCardDescription: '',
  OwnerDocumentNumber: '',
  InternationalDeliveryType: '',
  WarehouseSender: 'Відділення №15 (до 30 кг): вул. Героїв УПА, 6',
  WarehouseRecipientRef: '7ddcc4e5-c432-11e1-86b4-0026b97ed48a',
  Status: 'Відправлення отримано',
  StatusCode: '9',
  RefEW: 'acc06e3c-5111-11e8-aa3a-0025b501a04b',
  CreatedOnTheBasis: '',
  DatePayedKeeping: '',
};
